// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump/jump.proto

package com.acidonpe.jumpapp.grpc.proto;

public interface JumpReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jump.JumpReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated string jumps = 3;</code>
   * @return A list containing the jumps.
   */
  java.util.List<java.lang.String>
      getJumpsList();
  /**
   * <code>repeated string jumps = 3;</code>
   * @return The count of jumps.
   */
  int getJumpsCount();
  /**
   * <code>repeated string jumps = 3;</code>
   * @param index The index of the element to return.
   * @return The jumps at the given index.
   */
  java.lang.String getJumps(int index);
  /**
   * <code>repeated string jumps = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jumps at the given index.
   */
  com.google.protobuf.ByteString
      getJumpsBytes(int index);
}
