// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump/jump.proto

package com.acidonpe.jumpapp.grpc.proto;

/**
 * Protobuf type {@code jump.JumpReq}
 */
public final class JumpReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jump.JumpReq)
    JumpReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JumpReq.newBuilder() to construct.
  private JumpReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JumpReq() {
    message_ = "";
    jumps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JumpReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JumpReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            count_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jumps_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            jumps_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jumps_ = jumps_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acidonpe.jumpapp.grpc.proto.JumpProto.internal_static_jump_JumpReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acidonpe.jumpapp.grpc.proto.JumpProto.internal_static_jump_JumpReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acidonpe.jumpapp.grpc.proto.JumpReq.class, com.acidonpe.jumpapp.grpc.proto.JumpReq.Builder.class);
  }

  public static final int COUNT_FIELD_NUMBER = 1;
  private int count_;
  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JUMPS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList jumps_;
  /**
   * <code>repeated string jumps = 3;</code>
   * @return A list containing the jumps.
   */
  public com.google.protobuf.ProtocolStringList
      getJumpsList() {
    return jumps_;
  }
  /**
   * <code>repeated string jumps = 3;</code>
   * @return The count of jumps.
   */
  public int getJumpsCount() {
    return jumps_.size();
  }
  /**
   * <code>repeated string jumps = 3;</code>
   * @param index The index of the element to return.
   * @return The jumps at the given index.
   */
  public java.lang.String getJumps(int index) {
    return jumps_.get(index);
  }
  /**
   * <code>repeated string jumps = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jumps at the given index.
   */
  public com.google.protobuf.ByteString
      getJumpsBytes(int index) {
    return jumps_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (count_ != 0) {
      output.writeInt32(1, count_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < jumps_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jumps_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, count_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < jumps_.size(); i++) {
        dataSize += computeStringSizeNoTag(jumps_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getJumpsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acidonpe.jumpapp.grpc.proto.JumpReq)) {
      return super.equals(obj);
    }
    com.acidonpe.jumpapp.grpc.proto.JumpReq other = (com.acidonpe.jumpapp.grpc.proto.JumpReq) obj;

    if (getCount()
        != other.getCount()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getJumpsList()
        .equals(other.getJumpsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getJumpsCount() > 0) {
      hash = (37 * hash) + JUMPS_FIELD_NUMBER;
      hash = (53 * hash) + getJumpsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acidonpe.jumpapp.grpc.proto.JumpReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acidonpe.jumpapp.grpc.proto.JumpReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jump.JumpReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jump.JumpReq)
      com.acidonpe.jumpapp.grpc.proto.JumpReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acidonpe.jumpapp.grpc.proto.JumpProto.internal_static_jump_JumpReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acidonpe.jumpapp.grpc.proto.JumpProto.internal_static_jump_JumpReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acidonpe.jumpapp.grpc.proto.JumpReq.class, com.acidonpe.jumpapp.grpc.proto.JumpReq.Builder.class);
    }

    // Construct using com.acidonpe.jumpapp.grpc.proto.JumpReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      count_ = 0;

      message_ = "";

      jumps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acidonpe.jumpapp.grpc.proto.JumpProto.internal_static_jump_JumpReq_descriptor;
    }

    @java.lang.Override
    public com.acidonpe.jumpapp.grpc.proto.JumpReq getDefaultInstanceForType() {
      return com.acidonpe.jumpapp.grpc.proto.JumpReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.acidonpe.jumpapp.grpc.proto.JumpReq build() {
      com.acidonpe.jumpapp.grpc.proto.JumpReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acidonpe.jumpapp.grpc.proto.JumpReq buildPartial() {
      com.acidonpe.jumpapp.grpc.proto.JumpReq result = new com.acidonpe.jumpapp.grpc.proto.JumpReq(this);
      int from_bitField0_ = bitField0_;
      result.count_ = count_;
      result.message_ = message_;
      if (((bitField0_ & 0x00000001) != 0)) {
        jumps_ = jumps_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.jumps_ = jumps_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acidonpe.jumpapp.grpc.proto.JumpReq) {
        return mergeFrom((com.acidonpe.jumpapp.grpc.proto.JumpReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acidonpe.jumpapp.grpc.proto.JumpReq other) {
      if (other == com.acidonpe.jumpapp.grpc.proto.JumpReq.getDefaultInstance()) return this;
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.jumps_.isEmpty()) {
        if (jumps_.isEmpty()) {
          jumps_ = other.jumps_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureJumpsIsMutable();
          jumps_.addAll(other.jumps_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.acidonpe.jumpapp.grpc.proto.JumpReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.acidonpe.jumpapp.grpc.proto.JumpReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int count_ ;
    /**
     * <code>int32 count = 1;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 1;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList jumps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureJumpsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jumps_ = new com.google.protobuf.LazyStringArrayList(jumps_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @return A list containing the jumps.
     */
    public com.google.protobuf.ProtocolStringList
        getJumpsList() {
      return jumps_.getUnmodifiableView();
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @return The count of jumps.
     */
    public int getJumpsCount() {
      return jumps_.size();
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param index The index of the element to return.
     * @return The jumps at the given index.
     */
    public java.lang.String getJumps(int index) {
      return jumps_.get(index);
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the jumps at the given index.
     */
    public com.google.protobuf.ByteString
        getJumpsBytes(int index) {
      return jumps_.getByteString(index);
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param index The index to set the value at.
     * @param value The jumps to set.
     * @return This builder for chaining.
     */
    public Builder setJumps(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureJumpsIsMutable();
      jumps_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param value The jumps to add.
     * @return This builder for chaining.
     */
    public Builder addJumps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureJumpsIsMutable();
      jumps_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param values The jumps to add.
     * @return This builder for chaining.
     */
    public Builder addAllJumps(
        java.lang.Iterable<java.lang.String> values) {
      ensureJumpsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, jumps_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJumps() {
      jumps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string jumps = 3;</code>
     * @param value The bytes of the jumps to add.
     * @return This builder for chaining.
     */
    public Builder addJumpsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureJumpsIsMutable();
      jumps_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:jump.JumpReq)
  }

  // @@protoc_insertion_point(class_scope:jump.JumpReq)
  private static final com.acidonpe.jumpapp.grpc.proto.JumpReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acidonpe.jumpapp.grpc.proto.JumpReq();
  }

  public static com.acidonpe.jumpapp.grpc.proto.JumpReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JumpReq>
      PARSER = new com.google.protobuf.AbstractParser<JumpReq>() {
    @java.lang.Override
    public JumpReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JumpReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JumpReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JumpReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acidonpe.jumpapp.grpc.proto.JumpReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

