// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump/jump.proto

package com.acidonpe.jumpapp.grpc.proto;

public final class JumpProto {
  private JumpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jump_JumpReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jump_JumpReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jump_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jump_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017jump/jump.proto\022\004jump\"8\n\007JumpReq\022\r\n\005co" +
      "unt\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\r\n\005jumps\030\003 \003(" +
      "\t\")\n\010Response\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002" +
      " \001(\t26\n\013JumpService\022\'\n\004Jump\022\r.jump.JumpR" +
      "eq\032\016.jump.Response\"\000BY\n\037com.acidonpe.jum" +
      "papp.grpc.protoB\tJumpProtoP\001Z)github.com" +
      "/acidonper/jump-app-protos/jumpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jump_JumpReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jump_JumpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jump_JumpReq_descriptor,
        new java.lang.String[] { "Count", "Message", "Jumps", });
    internal_static_jump_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jump_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jump_Response_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
