// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump/jump.proto

package com.acidonpe.jumpapp.grpc.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jump.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
