// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.14.0
// source: jump/jump.proto

package jump

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count   int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Jumps   []string `protobuf:"bytes,3,rep,name=jumps,proto3" json:"jumps,omitempty"`
}

func (x *Jump) Reset() {
	*x = Jump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jump) ProtoMessage() {}

func (x *Jump) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jump.ProtoReflect.Descriptor instead.
func (*Jump) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{0}
}

func (x *Jump) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Jump) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Jump) GetJumps() []string {
	if x != nil {
		return x.Jumps
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JumpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jump *Jump `protobuf:"bytes,1,opt,name=jump,proto3" json:"jump,omitempty"`
}

func (x *JumpReq) Reset() {
	*x = JumpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpReq) ProtoMessage() {}

func (x *JumpReq) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpReq.ProtoReflect.Descriptor instead.
func (*JumpReq) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{2}
}

func (x *JumpReq) GetJump() *Jump {
	if x != nil {
		return x.Jump
	}
	return nil
}

type JumpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *JumpRes) Reset() {
	*x = JumpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpRes) ProtoMessage() {}

func (x *JumpRes) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpRes.ProtoReflect.Descriptor instead.
func (*JumpRes) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{3}
}

func (x *JumpRes) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_jump_jump_proto protoreflect.FileDescriptor

var file_jump_jump_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x75, 0x6d, 0x70, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x22, 0x4c, 0x0a, 0x04, 0x4a, 0x75, 0x6d, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6a, 0x75, 0x6d, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x75, 0x6d, 0x70, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x29, 0x0a, 0x07, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x6a, 0x75,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e,
	0x4a, 0x75, 0x6d, 0x70, 0x52, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x22, 0x35, 0x0a, 0x07, 0x4a, 0x75,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x35, 0x0a, 0x0b, 0x4a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x4a, 0x75, 0x6d, 0x70, 0x12, 0x0d, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e,
	0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x4a,
	0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x69, 0x64, 0x6f, 0x6e, 0x70, 0x65, 0x72,
	0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jump_jump_proto_rawDescOnce sync.Once
	file_jump_jump_proto_rawDescData = file_jump_jump_proto_rawDesc
)

func file_jump_jump_proto_rawDescGZIP() []byte {
	file_jump_jump_proto_rawDescOnce.Do(func() {
		file_jump_jump_proto_rawDescData = protoimpl.X.CompressGZIP(file_jump_jump_proto_rawDescData)
	})
	return file_jump_jump_proto_rawDescData
}

var file_jump_jump_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jump_jump_proto_goTypes = []interface{}{
	(*Jump)(nil),     // 0: jump.Jump
	(*Response)(nil), // 1: jump.Response
	(*JumpReq)(nil),  // 2: jump.JumpReq
	(*JumpRes)(nil),  // 3: jump.JumpRes
}
var file_jump_jump_proto_depIdxs = []int32{
	0, // 0: jump.JumpReq.jump:type_name -> jump.Jump
	1, // 1: jump.JumpRes.response:type_name -> jump.Response
	2, // 2: jump.JumpService.Jump:input_type -> jump.JumpReq
	3, // 3: jump.JumpService.Jump:output_type -> jump.JumpRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jump_jump_proto_init() }
func file_jump_jump_proto_init() {
	if File_jump_jump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jump_jump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jump_jump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jump_jump_proto_goTypes,
		DependencyIndexes: file_jump_jump_proto_depIdxs,
		MessageInfos:      file_jump_jump_proto_msgTypes,
	}.Build()
	File_jump_jump_proto = out.File
	file_jump_jump_proto_rawDesc = nil
	file_jump_jump_proto_goTypes = nil
	file_jump_jump_proto_depIdxs = nil
}
