// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.14.0
// source: jump/jump.proto

package jump

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LastPath string           `protobuf:"bytes,2,opt,name=last_path,json=lastPath,proto3" json:"last_path,omitempty"`
	JumpPath string           `protobuf:"bytes,3,opt,name=jump_path,json=jumpPath,proto3" json:"jump_path,omitempty"`
	Jumps    []*Jump_JumpStep `protobuf:"bytes,4,rep,name=jumps,proto3" json:"jumps,omitempty"`
}

func (x *Jump) Reset() {
	*x = Jump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jump) ProtoMessage() {}

func (x *Jump) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jump.ProtoReflect.Descriptor instead.
func (*Jump) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{0}
}

func (x *Jump) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Jump) GetLastPath() string {
	if x != nil {
		return x.LastPath
	}
	return ""
}

func (x *Jump) GetJumpPath() string {
	if x != nil {
		return x.JumpPath
	}
	return ""
}

func (x *Jump) GetJumps() []*Jump_JumpStep {
	if x != nil {
		return x.Jumps
	}
	return nil
}

type PerformJumpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jump *Jump `protobuf:"bytes,1,opt,name=jump,proto3" json:"jump,omitempty"`
}

func (x *PerformJumpReq) Reset() {
	*x = PerformJumpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerformJumpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformJumpReq) ProtoMessage() {}

func (x *PerformJumpReq) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformJumpReq.ProtoReflect.Descriptor instead.
func (*PerformJumpReq) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{1}
}

func (x *PerformJumpReq) GetJump() *Jump {
	if x != nil {
		return x.Jump
	}
	return nil
}

type FinalJumpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinalJumpReq) Reset() {
	*x = FinalJumpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalJumpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalJumpReq) ProtoMessage() {}

func (x *FinalJumpReq) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalJumpReq.ProtoReflect.Descriptor instead.
func (*FinalJumpReq) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{2}
}

type JumpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *JumpRes_JumpResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *JumpRes) Reset() {
	*x = JumpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpRes) ProtoMessage() {}

func (x *JumpRes) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpRes.ProtoReflect.Descriptor instead.
func (*JumpRes) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{3}
}

func (x *JumpRes) GetResponse() *JumpRes_JumpResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type Jump_JumpStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jump string `protobuf:"bytes,1,opt,name=jump,proto3" json:"jump,omitempty"`
}

func (x *Jump_JumpStep) Reset() {
	*x = Jump_JumpStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jump_JumpStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jump_JumpStep) ProtoMessage() {}

func (x *Jump_JumpStep) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jump_JumpStep.ProtoReflect.Descriptor instead.
func (*Jump_JumpStep) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Jump_JumpStep) GetJump() string {
	if x != nil {
		return x.Jump
	}
	return ""
}

type JumpRes_JumpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JumpRes_JumpResponse) Reset() {
	*x = JumpRes_JumpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jump_jump_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpRes_JumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpRes_JumpResponse) ProtoMessage() {}

func (x *JumpRes_JumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jump_jump_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpRes_JumpResponse.ProtoReflect.Descriptor instead.
func (*JumpRes_JumpResponse) Descriptor() ([]byte, []int) {
	return file_jump_jump_proto_rawDescGZIP(), []int{3, 0}
}

func (x *JumpRes_JumpResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JumpRes_JumpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_jump_jump_proto protoreflect.FileDescriptor

var file_jump_jump_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x75, 0x6d, 0x70, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x22, 0xa5, 0x01, 0x0a, 0x04, 0x4a, 0x75, 0x6d, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x75, 0x6d, 0x70, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x75, 0x6d, 0x70,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x05, 0x6a, 0x75, 0x6d, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x2e,
	0x4a, 0x75, 0x6d, 0x70, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x6a, 0x75, 0x6d, 0x70, 0x73, 0x1a,
	0x1e, 0x0a, 0x08, 0x4a, 0x75, 0x6d, 0x70, 0x53, 0x74, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x75, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x22,
	0x30, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x04, 0x6a, 0x75, 0x6d,
	0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65,
	0x71, 0x22, 0x7f, 0x0a, 0x07, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x2e, 0x4a, 0x75,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x3c, 0x0a, 0x0c, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x75, 0x0a, 0x0b, 0x4a, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x34, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x4a, 0x75, 0x6d, 0x70,
	0x12, 0x14, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x4a,
	0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x4a, 0x75,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x4a, 0x75, 0x6d, 0x70, 0x12, 0x12, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x2e,
	0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x69, 0x64, 0x6f, 0x6e, 0x70, 0x65,
	0x72, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x2d, 0x61, 0x70, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jump_jump_proto_rawDescOnce sync.Once
	file_jump_jump_proto_rawDescData = file_jump_jump_proto_rawDesc
)

func file_jump_jump_proto_rawDescGZIP() []byte {
	file_jump_jump_proto_rawDescOnce.Do(func() {
		file_jump_jump_proto_rawDescData = protoimpl.X.CompressGZIP(file_jump_jump_proto_rawDescData)
	})
	return file_jump_jump_proto_rawDescData
}

var file_jump_jump_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jump_jump_proto_goTypes = []interface{}{
	(*Jump)(nil),                 // 0: jump.Jump
	(*PerformJumpReq)(nil),       // 1: jump.PerformJumpReq
	(*FinalJumpReq)(nil),         // 2: jump.FinalJumpReq
	(*JumpRes)(nil),              // 3: jump.JumpRes
	(*Jump_JumpStep)(nil),        // 4: jump.Jump.JumpStep
	(*JumpRes_JumpResponse)(nil), // 5: jump.JumpRes.JumpResponse
}
var file_jump_jump_proto_depIdxs = []int32{
	4, // 0: jump.Jump.jumps:type_name -> jump.Jump.JumpStep
	0, // 1: jump.PerformJumpReq.jump:type_name -> jump.Jump
	5, // 2: jump.JumpRes.response:type_name -> jump.JumpRes.JumpResponse
	1, // 3: jump.JumpService.PerformJump:input_type -> jump.PerformJumpReq
	2, // 4: jump.JumpService.FinalJump:input_type -> jump.FinalJumpReq
	3, // 5: jump.JumpService.PerformJump:output_type -> jump.JumpRes
	3, // 6: jump.JumpService.FinalJump:output_type -> jump.JumpRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jump_jump_proto_init() }
func file_jump_jump_proto_init() {
	if File_jump_jump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jump_jump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerformJumpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalJumpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jump_JumpStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jump_jump_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpRes_JumpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jump_jump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jump_jump_proto_goTypes,
		DependencyIndexes: file_jump_jump_proto_depIdxs,
		MessageInfos:      file_jump_jump_proto_msgTypes,
	}.Build()
	File_jump_jump_proto = out.File
	file_jump_jump_proto_rawDesc = nil
	file_jump_jump_proto_goTypes = nil
	file_jump_jump_proto_depIdxs = nil
}
